import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MockProvider from '@/config/msw/MockProvider';
import ClientProvider from '@/config/react-query/ClientProvider';
import CentralStoreProvider from '@/config/zustand/CentralStoreProvider';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function enableMocking() {
  if (process.env.NEXT_PUBLIC_API_MOCKING === 'enabled') {
    const { server } = await import('@/mocks/node');
    server.listen();
  }
}
enableMocking();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MockProvider>
          <CentralStoreProvider>
            <ClientProvider>
              {children}
            </ClientProvider>
          </CentralStoreProvider>
        </MockProvider>
      </body>
    </html>
  );
}
