import type { Metadata } from 'next';
import localFont from 'next/font/local';

import ClientProvider from '@/config/react-query/ClientProvider';
import CentralStoreProvider from '@/config/zustand/CentralStoreProvider';
import './globals.css';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.className} antialiased`}>
        <CentralStoreProvider>
          <ClientProvider>{children}</ClientProvider>
        </CentralStoreProvider>
      </body>
    </html>
  );
}
