import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientProvider from '@/config/react-query/ClientProvider';
import CentralStoreProvider from '@/config/zustand/CentralStoreProvider';
import { Header } from "@/components/common/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CentralStoreProvider>
          <ClientProvider>
            <Header />
            {children}
          </ClientProvider>
        </CentralStoreProvider>
      </body>
    </html>
  );
}
